version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: travel_buddy
      POSTGRES_PASSWORD: travel_buddy_pass
      POSTGRES_DB: travel_buddy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  
    environment:
      DATABASE_URL: postgresql://travel_buddy:travel_buddy_pass@postgres:5432/travel_buddy_db
      SECRET_KEY: your_secret_key_here
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: uvicorn travel_buddy.main:app --host 0.0.0.0 --port 8000 --reload  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app       
      - /app/node_modules      
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local
    command: npm run dev

volumes:
  postgres_data:
