version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: travel_buddy
      POSTGRES_PASSWORD: travel_buddy_pass
      POSTGRES_DB: travel_buddy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://travel_buddy:travel_buddy_pass@postgres:5432/travel_buddy_db
      SECRET_KEY: your_secret_key_here
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local

volumes:
  postgres_data: 